### ISSUE TITLE
Improve gitflow

### ISSUE THREAD

**Issue by ivanwolf15** [Papinotas-Desarrollo/phoenix-shared#363]
Having two branches has no effect because `phoenix-shared` do not have some sort of `phoenix-shared@develop` npm package to test the package in staging environment (correct me if I'm wrong).

The main app always downloads the master branch, i.e., having `develop` branch is an unnecessary workload. Hence we should be making PR's to `master`, updating `package.json`, then tagging the branch with each release.

**Comment by cabas** [comment]
i totally agree, since we're deprecating this package in the near future i think the suggestion is kind of unnecessary. 

For now simply skip using the develop branch.

**Comment by ivanwolf15** [comment]
Thats enough for me

**Comment by cabas** [comment]
Closing this
